name: Build and Push Docker Image (on tag)

on:
  push:
    tags:
      - '*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest  # Adjust OS as needed

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/nodejs-backend:${{ regex(github.ref, /refs\/tags\/(<tag_name>)/, captures.tag_name) }}  # Replace with your image name

      - name: Build cache cleanup (optional)
        uses: actions/cache@v3
        with:
          path: ~/.docker/cache  # Adjust path if needed
          key: ${{ runner.os }}-build-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-build-  # Wildcard to reuse cache across different tags

      - name: Set up Git
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'

      - name: Extract new tag
        id: extract_tag
        run: echo "::set-output name=TAG::${GITHUB_REF#refs/tags/}"

      - name: Update values.yaml in other repos
        env:
          PAT: ${{ secrets.PAT }}
        run: |
          REPOS=("vdt-be-helmChart")
          for repo in "${REPOS[@]}"; do
            git clone https://github:${{ secrets.PAT }}@github.com/theWorstSolution/$repo.git
            cd $repo
            sed -i 's/^  appVersion: .*/  appVersion: '${{ steps.extract_tag.outputs.TAG }}'/' values.yaml
            git add path/to/values.yaml
            git commit -m "Update image version to ${{ steps.extract_tag.outputs.TAG }}"
            git push https://github:${{ secrets.PAT }}@github.com/your-org/$repo.git
            cd ..
          done